name: Go

on:
  push:
    branches: [ main, lint_test ]
  pull_request:
    branches: [ main, lint_test ]

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        # differnt version on purpose until golangci-lint gains support for 1.18
        go-version: 1.17

    - name: Verify
      run: make verify
