name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  GO_VERSION: '1.18'
  # podman does exist on Ubuntu, but it's old and seems buggy
  RUNTIME: docker
jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Run unit tests
      run: make test

    - name: Run integration tests
      run: make test-database-integration

  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        # different version on purpose until golangci-lint gains support for 1.18
        go-version: 1.17

    - name: Verify
      run: make verify
